repository:
  name: adeliom-webcomponents
  description: A collection of professionally designed, every day UI components built on Web standards. Works with all framework as well as regular HTML/CSS/JS.
  topics: javascript, css, html, ui, webcomponents, ux, designsystem, lit
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: next
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true


labels:
  - name: bug
    color: "#d73a4a"
  - name: feature
    color: "#a2eeef"
  - name: unconfirmed
    color: "#e4e669"
  - name: github-actions
    color: "#e99695"
  - name: npm
    color: "#bfe5bf"
  - name: composer
    color: "#bfe5bf"
  - name: dependencies
    color: "#b4a8d1"
  - name: direct
    color: "#5319e7"
  - name: indirect
    color: "#eeeeee"
  - name: production
    color: "#ff7619"
  - name: development
    color: "#e99695"
  - name: security
    color: "#fbca04"
  - name: application
    color: "#fbca04"
  - name: backend
    color: "#fbca04"

#environments:
#    -   name: production
#        wait_timer: 5
#        deployment_branch_policy:
#            protected_branches: true
#    -   name: staging
#        deployment_branch_policy:
#            custom_branches:
#                - main
#                - develop

#branches:
#  - name: main
#    protection:
#      required_pull_request_reviews:
#        dismiss_stale_reviews: true
#        required_approving_review_count: 0
#        require_code_owner_reviews: true
#        dismissal_restrictions:
#          users: [ ]
#          teams: [ ]
#      required_status_checks:
#        strict: true
#        contexts: [ ]
#      enforce_admins: true
#      required_linear_history: true
#      restrictions:
#        apps: [ ]
#        users: [ ]
#        teams: [ ]
