# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Documentation

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: production
      host:
        required: true
        type: string
        default: webcomponents.adeliom.io
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: production
      host:
        required: true
        type: string
        default: webcomponents.adeliom.io

jobs:
  storybook:
    name: Storybook
    uses: ./.github/workflows/storybook.yml
    secrets: inherit

  build:
    needs: storybook
    name: Docker
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy:
    needs: build
    name: Deployement
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment || github.event.inputs.environment }}
      host: ${{ inputs.host || github.event.inputs.host }}
      branch: ${{ github.ref_name }}
